### ISSUE TITLE
Dereferencing subschemas by $id with $ref in the same file does not seem to work

### ISSUE THREAD

**Issue by elzawie** [networknt/json-schema-validator#255] opened 2020-02-24 14:07 UTC
Hi there,

I am using your library for JSON validation and it works pretty well so far, however now I encountered a potential issue while trying to reference the internally defined subschemas using combination of $id and $ref properties. Referencing subschemas using JSON pointers instead of ids works as expected. The concept I am trying to test is described under the below hyperlink:

https://json-schema.org/understanding-json-schema/structuring.html#using-id-with-ref

Using the same JSON schema and data file with the below online validators yield expected results - return error saying that the element of "cars" array is missing required properties. 

https://jsonschemalint.com/#!/version/draft-07/markup/json
https://www.jsonschemavalidator.net/

**JSON schema:**

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://graph.link/ecp/schema/CDF/garage.json",
    "type": "object",
    "properties": {
        "cars": {
            "type": "array",
            "items": {
                "$ref": "#car"
            }
        }
    },
    "definitions": {
        "car": {
            "$id": "#car",
            "type": "object",
            "properties": {
                "model": {
                    "type": "string"
                },
                "manufacturer": {
                    "$ref": "#manufacturer"
                }
            },
            "required": ["model", "manufacturer"]
        },
        "manufacturer": {
            "$id": "#manufacturer",
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "factories": {
                    "type": "array",
                    "items": {
                        "$ref": "#factory"
                    }
                }
            }
        },
        "factory": {
            "$id": "#factory",
            "type": "object",
            "properties": {
                "location": {
                    "$ref": "#location"
                }
            }
        },
        "location": {
            "$id": "#location",
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "employees": {
                    "type": "array",
                    "items": {
                        "$ref": "#employee"
                    }
                }
            },
            "additionalProperties": false
        },
        "employee": {
            "$id": "#employee",
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                }
            },
            "additionalProperties": true,
            "maxProperties": 3
        }
    }
}

```

**JSON data file:**

```json
{
    "cars": [
        {

        }
    ]
}

```

**Test code:**

```java

    protected JsonSchema getJsonSchemaFromStreamContent(InputStream schemaContent) {
        JsonSchemaFactory factory = JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V7);
        return factory.getSchema(schemaContent);
    }

   protected JsonNode getJsonNodeFromStreamContent(InputStream content) throws Exception {
        ObjectMapper mapper = new ObjectMapper();
        JsonNode node = mapper.readTree(content);
        return node;
    }

@Test
    public void shouldFailWhenRequiredPropertiesDoNotExistInReferencedSubSchema() throws Exception {
        String schemaPath = "/schema.json";
        String dataPath = "/data.json";
        InputStream schemaInputStream = getClass().getResourceAsStream(schemaPath);
        JsonSchema schema = getJsonSchemaFromStreamContent(schemaInputStream);
        InputStream dataInputStream = getClass().getResourceAsStream(dataPath);
        JsonNode node = getJsonNodeFromStreamContent(dataInputStream);
        Set<ValidationMessage> errors = schema.validate(node);
        Assert.assertEquals(2, errors.size());
    }
```

Thank you very much in advance

**Comment by stevehu** [comment] 2020-02-24 17:17
Based on the schema definition and the input data, there shouldn't be any error as I understand it. The cars are defined as an array but it is empty. So nothing needs to be validated given there is no limitation for the array and empty array is valid. Would you please try to add an invalid entry into the array and see if the $id and $ref work?

**Comment by elzawie** [comment] 2020-02-25 08:14
Thanks for promptly looking into this. Actually there is a "car" object inside the array and it should be validated. The errors should be thrown because this is an empty object which is missing the required properties.  Replacing "cars" array item reference by id with JSON pointer results in the below errors:

- $.cars[0].model: is missing but it is required
- $.cars[0].manufacturer: is missing but it is required


This can be achieved by replacing the below line:
` "$ref": "#car"`
with
`"$ref": "#/definitions/car"`

**Comment by stevehu** [comment] 2020-02-25 12:59
@elzawie I got you. There is an empty car object in the array that I missed when I looked at the JSON.  Yes. The "#/definitions/car" makes sense as it is defined as the full path. Thanks a lot for the patience and clarification.

**Comment by elzawie** [comment] 2020-03-03 13:35
@stevehu, do you plan to work on this issue soon or is it something that has to wait ?

**Comment by stevehu** [comment] 2020-03-03 13:51
I think "#/definitions/car" is the right syntax for reference. Do you have any documentation on using "#car" as a reference?

**Comment by elzawie** [comment] 2020-03-04 08:26
Hi @stevehu , you're right, using "#/definitions/car" is a proper syntax for dereferencing subschemas, however, according to the JSON schema specification it should also be possible to dereference subschemas by their ID.  This concept was introduced in Draft 4 and is described below: 

https://json-schema.org/understanding-json-schema/structuring.html#using-id-with-ref

**Comment by stevehu** [comment] 2020-03-04 18:16
@elzawie We do have some issues with $id reference with v6 and above. The test case for reference is ignored as we have some issues. Some of the issues are partially resolved with this https://github.com/networknt/json-schema-validator/issues/248 but I guess there are still some edge cases that are not considered. I am very busy with other projects at the moment and will take a look later. If you could help to debug the root cause and submit a PR, that would be great. Thanks.

**Comment by waizuwolf** [comment] 2020-03-05 09:32
@stevehu : I am also using this library for JSON validation and facing the same issue. I am facing the issue even after using `"$ref": "#/definitions/car"` in the schema. Please note that my schema adheres to Draft 6. Is this the expected behaviour?

**Closed** 2020-03-09 19:59 UTC

**Comment by stevehu** [comment] 2020-03-09 20:15
@elzawie @rzukowski has fixed the issue and there is a test case in the code base with your provided schema and data to confirm it is working. Please review and let us know if you have any questions.
