### ISSUE TITLE
Unknown MetaSchema: https://json-schema.org/draft/2020-12/schema

### ISSUE THREAD

**Issue by mtwalli** [networknt/json-schema-validator#427] opened 2021-08-04 12:01 UTC
I'm getting the following exception
```console
  Caused by: com.networknt.schema.JsonSchemaException: Unknown MetaSchema: https://json-schema.org/draft/2020-12/schema
        at com.networknt.schema.JsonSchemaFactory.findMetaSchemaForSchema(JsonSchemaFactory.java:287)
        at com.networknt.schema.JsonSchemaFactory.createValidationContext(JsonSchemaFactory.java:278)
        at com.networknt.schema.JsonSchemaFactory.newJsonSchema(JsonSchemaFactory.java:272)
        at com.networknt.schema.JsonSchemaFactory.getSchema(JsonSchemaFactory.java:302)
        at com.networknt.schema.JsonSchemaFactory.getSchema(JsonSchemaFactory.java:310)

```

while validating this  [schema](https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/release/1.0.1/DGC.combined-schema.json) 

Could you please support newer versions ? or how can I fix it ?

**Comment by stevehu** [comment] 2021-08-04 15:08
2020-12 is not supported at the moment. I would be happy if someone can submit a PR to add it. Just search 2019-09 to copy the implementation I guess.

**Comment by winne42** [comment] 2022-05-16 12:34
This is a duplicate of #380

**Closed** 2022-08-06 18:58 UTC
