### ISSUE TITLE
Cannot get the validation result with self-reference schema

### ISSUE THREAD

**Issue by lmichel** [networknt/json-schema-validator#13] opened 2016-12-21 12:43 UTC
Steve,

I'm trying to validate the following JSON node:
```json
{
"data": {"xxx": 5},
"tree": {"values: "zzz"}
}
```
against this schema:
```json
{
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "tree": { "$ref": "#/definitions/tree" }
  },
  "definitions": {
    "tree": {
      "type": "object",
      "properties": {
        "value": { "type": "string" },
        "branches": {
          "type": "array",
          "items": { "$ref": "#/definitions/tree" },
          "minItems": 1
        }
      },
      "required": ["value"]
    }
  }
}
```
The node is not valid since $tree has no member named  "value" (confirmed by http://www.jsonschemavalidator.net/)
My code is like this:
```java
        Set<ValidationMessage> errors = schema.validate(node);
        for(ValidationMessage validationMessage : errors ) {
        	System.out.println("Message : " + validationMessage);
        }       
```
with both node and schema created by methods XXXFromClasspath of the class BaseJsonSchemaValidatorTest (I made those methods public for this purpose)
The output is
```shell
13:18:27.422 [main] DEBUG com.networknt.schema.TypeValidator - validate( {"data":{"xxx":5},"tree":{"values":"zzz"}}, {"data":{"xxx":5},"tree":{"values":"zzz"}}, $)
13:18:27.432 [main] DEBUG c.n.schema.PropertiesValidator - validate( {"data":{"xxx":5},"tree":{"values":"zzz"}}, {"data":{"xxx":5},"tree":{"values":"zzz"}}, $)
13:20:13.264 [main] DEBUG com.networknt.schema.RefValidator - validate( {"values":"zzz"}, {"data":{"xxx":5},"tree":{"values":"zzz"}}, $.tree)
13:20:43.758 [main] DEBUG com.networknt.schema.TypeValidator - validate( {"values":"zzz"}, {"data":{"xxx":5},"tree":{"values":"zzz"}}, $.tree)
13:20:45.852 [main] DEBUG c.n.schema.PropertiesValidator - validate( {"values":"zzz"}, {"data":{"xxx":5},"tree":{"values":"zzz"}}, $.tree)
```
No error is detected!!
Did I do something wrong?
I tried to follow with a debugger. My understanding is that the error is detected but at some point one of the stacked validate() invocations generate a null message (I'm not sure at all!).

**Comment by lmichel** [comment] 2016-12-21 13:09
A bit further: the validation only fails when the schema contains a self-reference. If I remove it:
```json
{
	"type": "object",
	"properties": {
		"name": {
			"type": "string"
		},
		"tree": {
			"$ref": "#/definitions/tree"
		}
	},
	"required": [
		"name","tree"
	],
	"definitions": {
		"tree": {
			"type": "object",
			"properties": {
				"value": {
					"type": "string"
				},
				"branches": {
					"type": "array",
					"items": {
						"type": "string"
					},
					"minItems": 1
				}
			},
			"required": [
				"value"
			]
		}
	}
}
```
The validator reports a correct message for the following node:
```json
{
  "name": "xxx",
  "tree": { }
}
```
something like
```shell
Message : $.tree.value: is missing but it is required
```

**Comment by stevehu** [comment] 2017-01-09 14:27
More information can be found in #12 as the root cause is to support nested reference.

**Comment by stevehu** [comment] 2019-06-25 15:33
@lmichel We have made a lot of changes regarding the reference. Could you please test it again? Thanks.

**Comment by lmichel** [comment] 2019-06-26 12:02
I'm now a bit far from this issue, although still interested.  I'll check this ASAP

**Comment by stevehu** [comment] 2019-08-07 15:46
This issue has been resolved by @davidvisiedo in https://github.com/networknt/json-schema-validator/issues/180

**Closed by stevehu** 2019-08-07 15:46 UTC
Labels: enhancement, help wanted
