### ISSUE TITLE
urn:jsonschema:java:time:Instant is not supported as reference

### ISSUE THREAD

**Issue by matejsp** [networknt/json-schema-validator#100] opened 2018-09-10 20:20 UTC
There is error when validating using schema generated by jackson 2.9.6:

CODE:
```    @Test
    public void generateSchema() throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        JsonSchemaGenerator schemaGen = new JsonSchemaGenerator(mapper);
        JsonSchema schema = schemaGen.generateSchema(SampleEvent.class);
        String stringSchema = mapper.writeValueAsString(schema);
        JsonParser parser = mapper.getFactory().createParser(stringSchema);
        JsonNode schemaNode = parser.readValueAsTree();
        JsonSchemaFactory factory = JsonSchemaFactory.getInstance();
        com.networknt.schema.JsonSchema schemaOut = factory.getSchema(schemaNode);
    }
```

POJO:
```
    @lombok.Data
    public static class SampleEvent {

        private Instant dateFrom;

        private Instant dateTo;

    }
```

SCHEMA:
```
{
	"type": "object",
	"id": "urn:jsonschema:net:sample:SimpleEvent",
	"properties": {
		"dateFrom": {
			"type": "object",
			"id": "urn:jsonschema:java:time:Instant",
			"properties": {
				"nano": {
					"type": "integer"
				},
				"epochSecond": {
					"type": "integer"
				}
			}
		},
		"dateTo": {
			"type": "object",
			"$ref": "urn:jsonschema:java:time:Instant"
		}
	}
}
```

ERROR:
```Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.networknt.schema.RefValidator.obtainAbsolutePath(RefValidator.java:94)
	at com.networknt.schema.RefValidator.getRefSchema(RefValidator.java:60)
	at com.networknt.schema.RefValidator.<init>(RefValidator.java:45)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.networknt.schema.ValidatorTypeCode.newValidator(ValidatorTypeCode.java:121)
	at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:240)
	... 41 more
```

**Comment by stevehu** [comment] 2018-09-10 21:53
The current Jackson version we are using is 2.9.5. Have you tried with it? Just trying to narrow the issue to ensure that it is the Jackson version issue. Thanks.

**Comment by matejsp** [comment] 2018-09-30 05:46
It is the same with 2.9.5. It generates the same schema. It seems that RefValidator is not able to resolve the "$ref": "urn:jsonschema:java:time:Instant" using id used in the previous attribute.

**Comment by stevehu** [comment] 2019-01-22 03:46
I don't think we support `urn:jsonschema:java:time:Instant` in the validator. I have marked the issue with `help wanted`. Let's see if someone from the community can get it fixed.

**Comment by stevehu** [comment] 2019-06-25 15:25
@matejsp The library has been enhanced by @jawaff and @flozano to support URI and URN. Could you please try it out again? If possible, could you add you use case to the unit test? Whether it works for not, it will help us to get the issue resolved. Thanks.

**Comment by jawaff** [comment] 2019-06-25 20:37
@stevehu This example actually wouldn't work with what I put together. Only standard URL schemes and the 'classpath'/'resource' schemes are supported right now (that is all configured in the constructor of JsonSchemaFactory.Builder). Custom URI schemes need to have a URIFactory and URIFetcher injected into the JsonSchemaFactory.Builder.

Now that I'm looking into it more, I'm realizing that there's actually a spec for a 'urn' URI scheme (https://tools.ietf.org/html/rfc8141#section-2). I did not add support for that scheme, but it can easily be done by creating a URIFactory for it. However, users will need to supply their own URIFetcher for the 'urn' scheme because there's no standard way to fetch a URN from what I can tell.

**Comment by matejsp** [comment] 2019-09-16 06:16
There is still similar problem with urn resolving (**invalid segment for URI**).
URL factory: **public URI create(final String uri)**

This does not work:
```
return new URL(uri).toURI();
```

This works:
```
return new URI(uri);
```

The same goes regarding: public URI **create(final URI baseURI, final String segment)**

**Comment by jawaff** [comment] 2019-09-16 21:18
Hello, I'm away from my PC, but the URLFactory isn't for URNs. A URL is a
valid URI, but a URN is not a valid URL. We should have a URNFactory, but
we don't yet have built in support for URNs. It's possible to create your
own URIFactory and URIFetcher for URNs, but they need to be injected into
the JsonSchemaFactory.

**Comment by francesc79** [comment] 2020-03-19 08:23
@stevehu @jawaff about URNFactory you can add the possiblity for customize the URISchemeFactory in JsonSchemaFactory? or you are going intention to add URNFactory?

**Comment by stevehu** [comment] 2020-03-19 12:19
@francesc79 Thanks for making this issue float again. Frankly, I haven't looked at this issue for a while as I am busy with a lot of other issues. I think @jawaff is in the same situation. Would you be able to try it out and submit a PR? Personally, I don't have a preference for either solution.

**Comment by Arno538** [comment] 2020-04-16 16:23
I need to use a URN in the $id to identify the schema. Since version 1.0.30 this is not working anymore. We don't want the URN to be able to be fetched (retrievable) at all (otherwise we would use a URL). In the combineCurrentUriWithIds method a JsonSchemaException is thrown.

**Comment by stevehu** [comment] 2020-04-17 10:59
@Arno538 Thanks a lot for raising the issue. Given that it was working before 1.0.30, chances are some updates in 1.0.30 broke the feature. Would you be able to compare the code base and find out the root cause and get it fixed? Thanks.

**Comment by stevehu** [comment] 2024-02-01 17:22
I think this issue is resolved in the latest version. If not, let's reopen this issue to address it. Thanks.

**Closed by stevehu** 2024-02-01 17:22 UTC
Labels: enhancement, help wanted
