### ISSUE TITLE
Validator hang on validation

### ISSUE THREAD

**Issue by sginer** [networknt/json-schema-validator#44] opened 2017-10-19 10:06 UTC
Validator never comme back and give result.

I put schema and json file I used.

Regards

[localfile.zip](https://github.com/networknt/json-schema-validator/files/1397946/localfile.zip)

**Comment by stevehu** [comment] 2017-10-20 02:13
@sginer Thanks for your schema and test json. I see you have a very big schema with over 30K lines and I remember there is another user had the same issue before with a very big schema. I think the problem is we are loading and compiling the entire schema into memory in order to speed up the validation and if the schema is too big, it might not be performing. I will create a test case and try to get it fixed; however, it will take some time as I have other projects that need urgent attentions. Let's keep this issue open until we have the result.

**Comment by stevehu** [comment] 2017-10-20 02:14
This is the same issue like #28 but with test schema and test data to reproduce the issue.

**Comment by cncqycy** [comment] 2017-10-24 06:02
i have the same problem. I think it's the "$ref" cause some infinite loop.
here is my json schema:
`{
  "type":"array"
  ,"items":{"$ref":"#/definitions/compositeFilterSchema"}
  ,"additionalItems": false
  ,"minItems": 1
  ,"maxItems": 10
  ,"uniqueItems": true
  ,"definitions":
  {
    "compositeFilterSchema":{
      "anyOf":[
        {"$ref":"#/definitions/simpleFilterSchema"}
        ,{"$ref":"#/definitions/logicalAndSchema"}
        ,{"$ref":"#/definitions/logicalOrSchema"}
      ]
    }
    ,"simpleFilterSchema":
    {
      "properties":
      {
        "col":{
          "type":"string"
        }
        ,"op":{
          "type":"string"
          ,"enum":["eq","neq","match",""]
        }
        ,"val":{
          "oneOf":[
            {"type":"string"}
            ,{"type":"number"}
            ,{
              "type":"array"
              ,"minItems":1
              ,"maxItems":100
              ,"uniqueItems": true
              ,"items":{
                "anyOf":[
                  {"type":"string"}
                  ,{"type":"number"}
                ]
              }
            }
          ]
        }
      }
      ,"additionalProperties":false
      ,"required":["column","op"]
    }
    ,"logicalAndSchema":
    {
      "properties":
      {
        "and":{"$ref":"#/definitions/compositeFilterSchema"}
      }
    }
    ,"logicalOrSchema":
    {
      "properties":
      {
        "or":{"$ref":"#/definitions/compositeFilterSchema"}
      }
    }
  }
}`

**Comment by cncqycy** [comment] 2017-10-24 06:04
@stevehu 
i have the same problem. I think it's the "$ref" cause some infinite loop.
Here is my json schema:
`{
  "type":"array"
  ,"items":{"$ref":"#/definitions/compositeFilterSchema"}
  ,"additionalItems": false
  ,"minItems": 1
  ,"maxItems": 10
  ,"uniqueItems": true
  ,"definitions":
  {
    "compositeFilterSchema":{
      "anyOf":[
        {"$ref":"#/definitions/simpleFilterSchema"}
        ,{"$ref":"#/definitions/logicalAndSchema"}
        ,{"$ref":"#/definitions/logicalOrSchema"}
      ]
    }
    ,"simpleFilterSchema":
    {
      "properties":
      {
        "col":{
          "type":"string"
        }
        ,"op":{
          "type":"string"
          ,"enum":["eq","neq","match",""]
        }
        ,"val":{
          "oneOf":[
            {"type":"string"}
            ,{"type":"number"}
            ,{
              "type":"array"
              ,"minItems":1
              ,"maxItems":100
              ,"uniqueItems": true
              ,"items":{
                "anyOf":[
                  {"type":"string"}
                  ,{"type":"number"}
                ]
              }
            }
          ]
        }
      }
      ,"additionalProperties":false
      ,"required":["column","op"]
    }
    ,"logicalAndSchema":
    {
      "properties":
      {
        "and":{"$ref":"#/definitions/compositeFilterSchema"}
      }
    }
    ,"logicalOrSchema":
    {
      "properties":
      {
        "or":{"$ref":"#/definitions/compositeFilterSchema"}
      }
    }
  }
}`

**Comment by cncqycy** [comment] 2017-10-24 06:04
**1
2
2**

**Comment by cncqycy** [comment] 2017-10-24 06:05
@stevehu 
i have the same problem. I think it's the "$ref" cause some infinite loop.
Here is my json schema:
**{
  "type":"array"
  ,"items":{"$ref":"#/definitions/compositeFilterSchema"}
  ,"additionalItems": false
  ,"minItems": 1
  ,"maxItems": 10
  ,"uniqueItems": true
  ,"definitions":
  {
    "compositeFilterSchema":{
      "anyOf":[
        {"$ref":"#/definitions/simpleFilterSchema"}
        ,{"$ref":"#/definitions/logicalAndSchema"}
        ,{"$ref":"#/definitions/logicalOrSchema"}
      ]
    }
    ,"simpleFilterSchema":
    {
      "properties":
      {
        "col":{
          "type":"string"
        }
        ,"op":{
          "type":"string"
          ,"enum":["eq","neq","match",""]
        }
        ,"val":{
          "oneOf":[
            {"type":"string"}
            ,{"type":"number"}
            ,{
              "type":"array"
              ,"minItems":1
              ,"maxItems":100
              ,"uniqueItems": true
              ,"items":{
                "anyOf":[
                  {"type":"string"}
                  ,{"type":"number"}
                ]
              }
            }
          ]
        }
      }
      ,"additionalProperties":false
      ,"required":["column","op"]
    }
    ,"logicalAndSchema":
    {
      "properties":
      {
        "and":{"$ref":"#/definitions/compositeFilterSchema"}
      }
    }
    ,"logicalOrSchema":
    {
      "properties":
      {
        "or":{"$ref":"#/definitions/compositeFilterSchema"}
      }
    }
  }
}**

**Comment by stevehu** [comment] 2017-10-24 11:06
@cncqycy Thanks for you schema. It helps us to narrow the focus.

**Comment by aritrac** [comment] 2018-09-17 11:57
Hi @stevehu is this issue fixed in the latest release? I am having kind of same issue where there are additioanl $refs within a definition pointing to the parent definition. So some kindof cyclic dependency issue is there. Please let me know if you need any further details.

Thanks

**Comment by stevehu** [comment] 2018-09-17 15:21
I think this is fixed already. I have a test case for the circular Sep but it would be good if you could submit your test case to ensure that it works for your schema. Thanks.

**Comment by aritrac** [comment] 2018-09-18 05:01
Hi @stevehu , thank you for your reply. I am providing the schema which is making the parser hang. It would be great if you can have a look. Thanks a lot for your time and help again

{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "title" : "Recursion-with-two-arrays",
  "type" : "object",
  "additionalProperties" : false,
  "properties" : {
    "first" : {
      "$ref" : "#/definitions/A"
    }
  },
  "definitions" : {
    "A" : {
      "type" : "object",
      "additionalProperties" : false,
      "properties" : {
        "one" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/A"
          }
        },
        "two" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/A"
          }
        }
      }
    }
  }
}

**Comment by aritrac** [comment] 2018-09-18 07:17
Also if it might help you, we are currently using 0.1.6 version @stevehu

**Comment by stevehu** [comment] 2018-09-18 11:14
@aritrac I will create a new test case in the develop branch and test it. Thanks.

**Comment by aritrac** [comment] 2018-09-18 12:01
@stevehu No issues, please let me know any tentative time when you are planning for the next release for the json-schema-validator. Thanks for your efforts for the same.

**Comment by aritrac** [comment] 2018-10-12 05:09
@stevehu would you please let us know if this bug is fixed?

**Comment by stevehu** [comment] 2018-10-12 13:00
@aritrac This is still not fixed yet. I was planning to rewrite this library with json-overlay but need to get at least several days to do so. It is hard to squeeze at the moment and I have marked this as help wanted. Hopefully, someone from the community can take an action. Thanks.

**Comment by stevehu** [comment] 2019-08-07 15:40
This should be addressed by @davidvisiedo in https://github.com/networknt/json-schema-validator/issues/180

**Closed by stevehu** 2019-08-07 15:40 UTC
Labels: bug, help wanted
