### ISSUE TITLE
CollectorContext is empty in `walk` return value

### ISSUE THREAD

**Issue by timocov** [networknt/json-schema-validator#849] opened 2023-08-12 21:38 UTC
Having `isResetCollectorContext=true` is a good way to keep collector context "pure" between runs. But if you need to get collector context, the only option you have is to set `isResetCollectorContext` to `false` and then reset the context manually after you're done. It is so because of [this code](https://github.com/networknt/json-schema-validator/blob/3ff32ee3fbb1c6287c6dfeda14a8bdeb965ef6c3/src/main/java/com/networknt/schema/JsonSchema.java#L518-L523) - while the library copies collector context into `ValidationResult`, it keeps its reference and when execution reaches `finally` block it will reset the context in both returned value and actual "current" state. `CollectorContext` [creates new objects on reset](https://github.com/networknt/json-schema-validator/blob/3ff32ee3fbb1c6287c6dfeda14a8bdeb965ef6c3/src/main/java/com/networknt/schema/CollectorContext.java#L219-L220), but as soon as we're keeping the reference to the same `CollectorContext` object in `ValidationResult` it will be reset everywhere.

I don't know if it was done intentionally, but it looks like a bug for me and probably `ValidationResult` should have a copy of `CollectorContext`. Otherwise you have to do something like this:

```java
try {
    ValidationResult result = schema.walk(object, true);
    // do something here
} finally {
    schema.getCollectorContext().reset();
}
```

i.e. sort of replicate the code that the library already has. Additionally, you can easily forget to reset it in some places (if you do multiple operations with the schema in different functions, and `isResetCollectorContext` is assigned at the schema creation so you have to either use multiple schemas that are different in this flag only or somehow make sure that you always reset the context).

**Comment by stevehu** [comment] 2023-08-25 16:43
I think we do that to avoid out-of-memory issues with some schemas.

**Comment by timocov** [comment] 2023-08-27 11:52
Hi @stevehu, thanks for the reply. I understand the intention, but it feels like both problems could be solved by either making a shallow copy of collector context (for performance and memory usage reasons I don't think that making a deep copy makes sense to do) - just copy references of data and then on reset create new objects (it's already done there btw).

I can create a PR with the proposed fix, probably it would be better for discussing and seeing possible implications there. Would this work?

**Comment by stevehu** [comment] 2023-08-28 01:43
Making a shallow copy is not the answer, as it can hold the reference to block the objects to be GCed. I think the issue is when we should reset the collector. I agree that we shouldn't reset in the final block right after the return of ValidationResult. It wasn't an issue before because nobody was using the collectorContext before. If we don't reset in the finally block, where is the best place?

**Comment by timocov** [comment] 2023-08-28 06:59
> as it can hold the reference to block the objects to be GCed

It would prevent it from being GCed only if a caller would keep ValidationResult object in their code for longer than current execution frame right? Isn't it expected behaviour for any program (you keep an object - it won't be GCed)? Once you forget the result object it can be collected right away.

**Comment by stevehu** [comment] 2023-08-28 12:24
Once we return the ValidationResult, we don't have control over how this object can be used or released.

**Comment by timocov** [comment] 2023-08-28 23:09
> Once we return the ValidationResult, we don't have control over how this object can be used or released

Exactly, I personally don't think that this library should solve out-of-memory issues _caused by external code_, i.e. the library can guarantee that it doesn't have any memory footprint internally after `walk` run. Yes, if consumer's code handles a reference to full `ValidationResult` object (or even `CollectorContext`) - it shouldn't be a problem of this library as you have no control over it. If it is so, then the library shouldn't worry about this issue and can provide better API.

**Comment by stevehu** [comment] 2023-08-30 13:12
This is the issue that we were facing. If you can ensure the issue is resolved with a new solution, I am OK. 

https://github.com/networknt/json-schema-validator/issues/810

**Comment by holgpar** [comment] 2023-10-12 09:32
I have followed: https://github.com/networknt/json-schema-validator/blob/master/doc/collector-context.md and was not getting it to work without setting:

```
    configuration.setResetCollectorContext(false);
```

Does the documentation need to be updated?

**Comment by stevehu** [comment] 2023-10-12 18:02
@holgpar I think you are right. We need to update the document. Could you please create a PR?

**Comment by holgpar** [comment] 2023-10-14 13:47
Sure, I will describe the current behavior. But I also agree with @timocov that there is no contradiction in the library

- not holding on to references to collectors in its internal (thread local) state (i.e. not leaking memory)
- returning references to collectors to a caller

a library returning newly created collections to a caller is a very common thing. I might attempt to provide a PR once I am more familiar with the code.

**Comment by timocov** [comment] 2023-10-16 21:00
Hi @stevehu,

I finally found some time to create a PR with fixes that I think should address the issue and avoid memory leaks, see https://github.com/networknt/json-schema-validator/pull/878.

I added some tests (they pass locally), I hope at least the idea of what I meant is clear from the changes, but I'm ready to elaborate if needed.

I'm not too sure the documentation changes, so any input or help would be appreciated 🙏 

Let me know what do you think.

**Closed** 2023-12-07 23:21 UTC
